build: off

environment:
  TWINE_PASSWORD:
    secure: A6ZaqP7tk1HfcTFRqGY/xP4nFZkNtSqXkq/zGGn84qim1HnD0vsVViC+f7fdvFNzNawwcX02WQyo9daVsFszLufliCcpjkbBiXwo4W4t/uPYqbHZuNHI5K1H5pTsPc8Yin+hKcuhYp3Wr2HCMti23muh9GnSDcoeybnfiiJlNoW+ntCg7AkpUiYCGWJfHG4wDbw2cQPWKq7dCFAh/HLAlR4Ccq9MNz5Bol7QDkBzHW5Lxc6HLbXRrLhUkkYr1KCp0qsSLmMHaWshDDzP6I2lcQ==

  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python38"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: "64"

install:
  - SET PATH=%PYTHON%;%PATH%
  - python --version
  - python -m pip install -r requirements.txt

test_script:
  - git submodule update --init --recursive
  - python setup.py test

after_test:
  - IF %APPVEYOR_REPO_TAG%==true git clean -dfx
  - IF %APPVEYOR_REPO_TAG%==true python -m pip install wheel twine
  - IF %APPVEYOR_REPO_TAG%==true python setup.py bdist_wheel
  - IF %APPVEYOR_REPO_TAG%==true python -m twine upload -u __token__ dist/*
